"""Regenerate the fully pinned requirement files from pyproject.toml.

requirements/server.txt  what the MCP server image installs
requirements/dev.txt     everything: server, agent and dev tools

Uses pip's resolver in dry-run mode, so nothing is installed.
"""

import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGETS = {"server.txt": ".", "dev.txt": ".[agent,dev]"}
HEADER = "# Generated by scripts/lock.py from pyproject.toml. Do not edit by hand.\n"


def resolve(spec: str) -> list[str]:
    with tempfile.TemporaryDirectory() as tmp:
        report = Path(tmp) / "report.json"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "pip",
                "install",
                "--dry-run",
                "--ignore-installed",
                "--quiet",
                "--report",
                str(report),
                spec,
            ],
            cwd=ROOT,
            check=True,
        )
        installs = json.loads(report.read_text())["install"]
    pins = {
        f"{item['metadata']['name'].lower()}=={item['metadata']['version']}"
        for item in installs
        if item["metadata"]["name"].lower() != "finance-ops-agents"
    }
    return sorted(pins)


def main() -> None:
    out_dir = ROOT / "requirements"
    out_dir.mkdir(exist_ok=True)
    for filename, spec in TARGETS.items():
        pins = resolve(spec)
        (out_dir / filename).write_text(HEADER + "\n".join(pins) + "\n")
        print(f"requirements/{filename}: {len(pins)} packages")


if __name__ == "__main__":
    main()
